name: MultiLingualEmbeddings
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python-annoy
  - _libgcc_mutex
  - attrs
  - blas
  - bleach
  - bokeh
  - ca-certificates
  - certifi
  - cudatoolkit
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - fastbpe
  - fontconfig
  - freetype
  - glib
  - gmp
  - gst-plugins-base
  - gstreamer
  - icu
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - kiwisolver
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgfortran-ng
  - libpng
  - libsodium
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - libxslt
  - lxml
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - mplcursors
  - nbconvert
  - nbformat
  - ncurses
  - ninja
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pcre
  - pillow
  - pip
  - prometheus_client
  - prompt_toolkit
  - pygments
  - pyparsing
  - pyqt
  - pyrsistent
  - python
  - python-dateutil
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - tensorflow
  - tensorflow-estimator
  - tensorflow-hub
  - terminado
  - testpath
  - tk
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - absl-py
    - astor
    - backcall
    - blis
    - cachetools
    - catalogue
    - cffi
    - chardet
    - cymem
    - cython
    # - faiss-gpu
    - gast
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - h5py
    - idna
    - ipdb
    - ipython-genutils
    - jedi
    - jieba
    - keras-applications
    - keras-preprocessing
    - livelossplot
    - llvmlite
    - markdown
    - mecab-python3
    - murmurhash
    - numba
    - oauthlib
    - opt-einsum
    - parso
    - patsy
    - pexpect
    - pickleshare
    - plac
    - portalocker
    - preshed
    - protobuf
    - ptyprocess
    - pyasn1
    - pyasn1-modules
    - pycparser
    - pynvml
    - pytorch-nlp
    - regex
    - requests
    - requests-oauthlib
    - rsa
    - sacrebleu
    - seaborn
    - sentencepiece
    - spacy
    - srsly
    - statsmodels
    - tabulate
    - tb-nightly
    - tbb
    - tensorboard
    - tensorflow-text
    - termcolor
    - tf-estimator-nightly
    - thinc
    - torch
    - tqdm
    - transliterate
    - typing
    - umap-learn
    - urllib3
    - wasabi
    - wcwidth
    - werkzeug
    - wordcloud
    - wrapt
    - yellowbrick